export const ActionTypes = {
	SET_LOADER: 'SET_LOADER',
	SET_SELECTED: "SET_SELECTED",
	SET_NUMBER_FLOORS: "SET_NUMBER_FLOORS",
	CALCULATE_LENGTH: 'CALCULATE_LENGTH',
	SUCCESS_DATA: 'SUCCESS_DATA',
	ERROR_DATA: 'ERROR_DATA',
	CLEAR_DATA: 'CLEAR_DATA'
}
